### ISSUE TITLE
High severity security vulnerability

### ISSUE THREAD

**Issue by jabrah** [eclipse-pass/pass-ember-adapter#36]
https://github.com/OA-PASS/ember-fedora-adapter/network/alert/package-lock.json/handlebars/open

Handlebars dependency should be updated to 4.1.2 or higher

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete.  This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
