### ISSUE TITLE
Update images in docker test environment

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/pass-ember-adapter#40]
Tests will fail with the latest fcrepo because of a CORS issue.  The newer fcrepo sets Access-Control-Allow-Origin to *.

The configuration in the fcrepo weblxml (see pass-docker) will need to be changed. Compare to the web.xml of previous versions. In particular look at cors.support.credential.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete.  This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
